# Generated by Django 5.0.7 on 2024-07-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mobile',
            new_name='asset_tag',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(db_column='emp_code', max_length=6, null=True),
        ),
    ]
