# Generated by Django 5.0.7 on 2024-07-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_rename_mobile_employee_asset_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='duration',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='default_value', max_length=6),
        ),
    ]
