# Generated by Django 5.0.6 on 2024-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_alter_employee_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=6)),
                ('sex', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
