# Generated by Django 5.0.6 on 2024-08-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0008_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='asset_tag',
            field=models.CharField(max_length=50),
        ),
    ]
