# Generated by Django 5.0.7 on 2024-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0009_alter_employee_asset_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assettag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=10)),
                ('display_name', models.CharField(max_length=50)),
                ('internal_reference', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=100)),
                ('quanlity', models.CharField(max_length=20)),
                ('asset_type', models.CharField(max_length=50)),
            ],
        ),
    ]
