# Generated by Django 5.0.7 on 2024-08-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0011_rename_assettag_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
