# Generated by Django 5.0.7 on 2024-08-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0012_rename_quanlity_equipment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
