# Generated by Django 5.1 on 2024-08-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0013_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='return_by',
            field=models.CharField(default='N/A', max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
