# Generated by Django 5.1.1 on 2024-10-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0014_employee_return_by_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('chat_id', models.CharField(max_length=20)),
                ('last_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
