# Generated by Django 5.1.1 on 2024-10-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0015_botdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botdetail',
            name='last_modify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
