# Generated by Django 5.1.1 on 2024-10-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0016_alter_botdetail_last_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
