# Generated by Django 5.1.1 on 2024-10-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0017_employee_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='model',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
